app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Testing Controller
Route::get('test', 'TestingController@index');

//Sitemap Controllers
Route::get('sitemap.xml', [
  //sitemap xml index
  'as'   => 'sitemap.root',
  'uses' => 'User\SitemapController@IndexXML'
  ]);
Route::get('category/sitemap.xml', [
  'as'   => 'sitemap.category',
  'uses' => 'User\SitemapController@CategoryXML'
  ]);
Route::get('catalog/sitemap.xml', [
  'as'   => 'sitemap.catalog',
  'uses' => 'User\SitemapController@CatalogXML'
  ]);
Route::get('about/sitemap.xml', [
  'as'   => 'sitemap.about',
  'uses' => 'User\SitemapController@AboutXML'
  ]);
Route::get('producer/sitemap.xml', [
  'as'   => 'sitemap.producer',
  'uses' => 'User\SitemapController@ProducerXML'
  ]);
Route::get('images/sitemap.xml', [
  'as'   => 'sitemap.image',
  'uses' => 'User\SitemapController@ImageXML'
  ]);

//Common Controllers
Route::get('images/{path}', [
  'as'   => 'images',
  'uses' => 'Common\ImageController@respond'
  ]);

//AJAXs
Route::get('images/', [
  'as'   => 'ajax.images.list',
  'uses' => 'Common\ImageController@jsonList'
  ]);
Route::get('products/', [
  'as'   => 'ajax.product.list',
  'uses' => 'Common\ProductController@jsonList'
  ]);

//FrontEnd Controllers
Route::get('/', [
  'as'   => 'root',
  'uses' => 'User\HomeController@index'
  ]);
Route::post('search/', [
  'as'   => 'search',
  'uses' => 'User\SearchController@index'
  ]);
Route::resource('category', 'User\ArticleCategoryController',[
  'only' => ['index', 'show']
  ]);
Route::resource('category.article', 'User\ArticleController', [
  'only' => ['index', 'show']
  ]);
Route::resource('catalog', 'User\ProductCategoryController', [
  'only' => ['index', 'show']
  ]);
Route::resource('catalog.product', 'User\ProductController', [
  'only' => ['index', 'show']
  ]);
Route::get('about/map', [
  'as'   => 'about.map',
  'uses' => 'User\AboutController@showMap'
  ]);
Route::resource('about', 'User\AboutController', [
  'only' => ['index']
  ]);
Route::resource('producer', 'User\ProducerController', [
  'only' => ['index', 'show']
  ]);

//Reset Password Controllers (accessible by victim)
  // Password reset routes...
  Route::get('password/reset/{token}', [
    'as'  => 'password.reset.token',
    'uses'=> 'Auth\PasswordController@getReset'
  ]);
  Route::post('password/reset', [
    'as'  => 'password.reset.post',
    'uses'=> 'Auth\PasswordController@postReset'
  ]);

//BackEnd Controllers (administrators)
Route::get('admin', [
  'as'   => 'admin.root',
  'uses' => 'Admin\UAuthController@home'
]);
Route::post('admin',[
  'as'   => 'admin.login',
  'uses' => 'Admin\UAuthController@login'
]);
Route::group(['middleware' => 'auth'], function(){
  Route::get('admin/logout',[
    'as'   => 'admin.logout',
    'uses' => 'Admin\UAuthController@logout'
  ]);
  //User Password Reset Controllers
    // Password reset link request routes...
    Route::get('admin/password/email', [
      'as'   => 'admin.password.reset',
      'uses' => 'Auth\PasswordController@getEmail'
    ]);
    Route::post('admin/password/email', [
      'as'   => 'admin.password.reset.post',
      'uses' => 'Auth\PasswordController@postEmail'
    ]);


  //Search Controller hooks
  Route::any('admin/category/search', [
    'as'    => 'admin.category.search',
    'uses'  => 'Admin\ArticleCategoryController@search'
  ]);
  Route::any('admin/catalog/search', [
    'as'    => 'admin.catalog.search',
    'uses'  => 'Admin\ProductCategoryController@search'
  ]);
  Route::any('admin/article/search', [
    'as'    => 'admin.article.search',
    'uses'  => 'Admin\ArticleController@search'
  ]);
  Route::any('admin/product/search', [
    'as'    => 'admin.product.search',
    'uses'  => 'Admin\ProductController@search'
  ]);
  Route::any('admin/user/search', [
    'as'    => 'admin.user.search',
    'uses'  => 'Admin\UserController@search'
  ]);
  Route::any('admin/image/search', [
    'as'    => 'admin.image.search',
    'uses'  => 'Admin\ImageController@search'
  ]);
  Route::any('admin/producer/search', [
    'as'    => 'admin.producer.search',
    'uses'  => 'Admin\ProducerController@search'
  ]);

  //Management Controllers
  Route::resource('admin/category', 'Admin\ArticleCategoryController', [

  ]);
  Route::resource('admin/article', 'Admin\ArticleController', [
    'except' => ['show']
  ]);
  Route::resource('admin/catalog', 'Admin\ProductCategoryController', [

  ]);
  Route::resource('admin/product', 'Admin\ProductController', [
    'except' => ['show']
  ]);
  Route::resource('admin/image', 'Admin\ImageController', [
    'only'   => ['index', 'store', 'update', 'destroy']
  ]);
  Route::resource('admin/authorities', 'Admin\AuthoritiesController',[
    'only'   => ['index', 'store', 'update', 'destroy']
  ]);
  Route::resource('admin/demographics', 'Admin\DemographicController', [
    'only'   => ['index', 'store', 'update', 'destroy']
  ]);
  Route::resource('admin/user', 'Admin\UserController',[
    'except' => ['destroy']
  ]);
  Route::resource('admin/producer', 'Admin\ProducerController', [
    'except' => ['show']
  ]);

});

app/Http/Controllers/Admin/UserController.php
<?php

namespace Pringgolayan\Http\Controllers\Admin;

use Illuminate\Http\Request;

use Pringgolayan\Http\Requests;
use Pringgolayan\Http\Controllers\Controller;

use Auth;
use Hash;
use Pringgolayan\Models\User;
use Pringgolayan\Models\Articles;

class UserController extends AdminUIController
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $Users = User::with('Article')->paginate(20);
        $Users->setPath(route('admin.user.index'));
        $array = [
          'Users' => $Users
        ];
        $array = $this->buildNavbar($array);
        return view('admin.daftar-user', $array);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $array = [
          'isEdit' => false
        ];
        $array = $this->buildNavbar($array);
        return view('admin.user', $array);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $username = $request->input('username');
        $password = $request->input('newPassword');
        $passwordC= $request->input('newPasswordC');
        $realname = $request->input('realname');
        $email    = $request->input('email');

        $nUser           = new User;
        $nUser->username = $username;
        $nUser->password = bcrypt($password);
        $nUser->realname = $realname;
        $nUser->email    = $email;
      if($request->has('username') && $request->has('newPassword') && $request->has('newPasswordC') && $request->has('realname')
         && $request->has('email'))
      {
        $oUser1   = User::where('username', '=', $username)->first();
        $oUser2   = User::where('email', '=', $email)->first();
        if(($oUser1 == null) && ($oUser2 == null))
        {
          if(strcmp($passwordC, $password) == 0)
          {
            $nUser->save();
            $request->session()->flash('success', 'Pengguna <strong>' . $nUser->realname . '</strong> telah ditambahkan');
            return redirect(route('admin.user.index'));
          }
          else
          {
            $request->session()->flash('alert', 'Pasangan password tidak cocok');
            $array = [
              'isEdit' => true,
              'User'   => $nUser,
            ];
            $array = $this->buildNavbar($array);
            return view('admin.user', $array);
          }
        }
        else
        {
          $request->session()->flash('alert', 'User dengan e-mail/username yang sama sudah ada');
          $array = [
            'isEdit' => true,
            'User'   => $nUser,
          ];
          $array = $this->buildNavbar($array);
          return view('admin.user', $array);
        }
      }
      $request->session()->flash('alert', 'Form harus diisi lengkap!');
      $array = [
        'isEdit' => true,
        'User' => $nUser
      ];
      $array = $this->buildNavbar($array);
      return view('admin.user', $array);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
      return view('admin.profil-user', $this->buildNavbar(['Post_count' => count(Articles::where('user_id', '=', $id)->get())]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      if($id == Auth::user()->id)
      {
        $array = [
          'isEdit' => true,
          'User'   => User::find($id)
        ];
        $array = $this->buildNavbar($array);
        return view('admin.user', $array);
      }
      else
      {
        return redirect(route('admin.user.index'));
      }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update($id, Request $request)
    {
      if($request->has('username') && $request->has('realname') && $request->has('email') && (Auth::user()->id == $id))
      {
        $username  = $request->input('username');
        $password  = $request->input('password');
        $Npassword = $request->input('newPassword');
        $NpasswordC= $request->input('newPasswordC');
        $realname  = $request->input('realname');
        $email     = $request->input('email');

        $oUser1   = User::where('username', '=', $username)->first();
        $oUser2   = User::where('email', '=', $email)->first();

        $nUser           = User::find($id);
        if(!$nUser)
        {
          abort(403);
        }

        $nUser->username = $username;
        if(($password != null) && ($Npassword != null) && ($NpasswordC != null))
        {
          //saves password if old password match and new passwords-confirmation pair match
          if((strcmp($Npassword, $NpasswordC) == 0) && (Hash::check($password, $oUser1->password)))
          {
            $nUser->password = bcrypt($Npassword);
          }
          else
          {
            $request->session()->flash('alert', 'Pasangan password tidak cocok');
            $array = [
              'isEdit' => true,
              'User'   => $nUser,
            ];
            $array = $this->buildNavbar($array);
            return view('admin.user', $array);
          }
        }
        $nUser->realname = $realname;
        $nUser->email    = $email;
        if((($oUser1->id == $id) && ($oUser2->id == $id)))
        {
          $nUser->update();
          $request->session()->flash('success', 'Pengguna <strong>' . $nUser->realname . '</strong> telah diperbarui');
          return redirect(route('admin.user.index'));
        }
        else
        {
          $request->session()->flash('alert', 'User dengan e-mail/username yang sama sudah ada');
          $array = [
            'isEdit' => true,
            'User'   => $nUser,
          ];
          $array = $this->buildNavbar($array);
          return view('admin.user', $array);
        }
      }
      $request->session()->flash('alert', 'Form harus diisi lengkap!');
      return redirect(route('admin.user.edit', $id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }

    public function search(Request $request)
    {
        $array =[
          'SearchTerm'     => '-',
          'Users'       => []
        ];
        if($request->has('term'))
        {
          $SearchTerm            = $request->input('term');
          $UserResults           = User::search($SearchTerm)->with('Article')->paginate(20);
          $UserResults->setPath(route('admin.user.search'));
          $UserResults->appends(['term' => $request->input('term')]);
          $array['SearchTerm']   = $SearchTerm;
          $array['Users']        = $UserResults;
          $request->session()->flash('success', 'Ditemukan <strong>' . $UserResults->total() . ' pengguna </strong> dengan' .
                                      ' kata kunci <strong>' . $SearchTerm . '</strong>');
        }
        else
        {
          return redirect(route('admin.user.index'));
        }
        $array = $this->buildNavbar($array);
        return view('admin.daftar-user', $array);
    }

}

app/Http/Controllers/User/AboutController.php
<?php

namespace Pringgolayan\Http\Controllers\User;

use Illuminate\Http\Request;

use Pringgolayan\Http\Requests;
use Pringgolayan\Http\Controllers\Controller;

use Pringgolayan\Models\Demographics;
use Pringgolayan\Models\Authorities;

class AboutController extends UserUIController
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $array =[
          'Demographics' => Demographics::with('Image')->get(),
          'Authorities'  => Authorities::with('Image')->orderBy('order', 'asc')->get()
        ];
        $array = $this->buildNavbar($array);
        return view("user.tentang", $array);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }

    public function showMap()
    {
      $array = [];
      $array = $this->buildNavbar($array);
      return view('user.peta', $array);
    }
}

app/Http/Controllers/User/ArticleCategoryController.php
<?php

namespace Pringgolayan\Http\Controllers\User;

use Illuminate\Http\Request;

use Pringgolayan\Http\Requests;
use Pringgolayan\Http\Controllers\Controller;

use Pringgolayan\Models\Articles;
use Pringgolayan\Models\ArticleCategories;

class ArticleCategoryController extends UserUIController
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $Categories = ArticleCategories::orderBy('name', 'asc')->paginate(10);
        $Categories->setPath(route('category.index'));
        $array = [
          'Categories' => $Categories
        ];
        $array = $this->BuildNavbar($array);
        return view('user.daftar-kategori', $array);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($slug)
    {
      //take input slugs instead of ids (for SEF)
      $Category   = ArticleCategories::where('slug', '=', $slug)->first();
      if($Category == null)
      {
        //fall back method
        $Category   = ArticleCategories::find($slug);
        if($Category == null)
        {
          //fall back and still no result, throw 404 - good luck
          return abort(404);
        }
      }
      $Posts       = $Category->Article()->orderBy('created_at', 'desc')->with('Image')->paginate(5);
      $Posts->setPath(route('category.show', $slug));
      $array = [
        'Category' => $Category,
        'Posts'    => $Posts
      ];
      $array = $this->BuildNavbar($array);
      return view('user.kategori', $array);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/layouts/carousel.blade.php
{{--
  Required: $Posts contains list of post (preferrably 5 or 10)
--}}

<!-- Slider Begin -->
<div class="hidden-sm hidden-xs" id="slider1_container" style="position: relative; margin: 0 auto; top: -20px; left: 0px; width: 1300px; height: 500px; overflow: hidden;">
  <!-- Loading Screen -->
  <div u="loading" style="position: absolute; top: 0px; left: 0px;">
    <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
    <div style="position: absolute; display: block; background: url(assets/img/loading.gif) no-repeat center center; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
  </div>
  <!-- Slides Container -->
  <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1300px; height: 500px; overflow: hidden;">
    @foreach($Posts as $Post)
    <div>
      @if($Post->intro_image != null)
      <img u="image" src="{{ route('images', $Post->Image->image_path) }}" alt="{{ $Post->Image->description }}" />
      @else
      <img u="image" src="{{ route('images', 'noImage.png') }}" alt="{{ $Post->title }}" />
      @endif
      <div style="position: absolute; width: 480px; height: 120px; top: 30px; left: 30px; padding: 5px; text-align: left; line-height: 60px; text-transform: uppercase; font-size: 50px; color: #FFFFFF;">
        <span style="background-color: rgba(0, 0, 0, 0.7); padding: 0.5px;">
        {{ str_limit($Post->title, 25) }}
        </span>
      </div>
      <div style="position: absolute; width: 480px; height: 120px; top: 300px; left: 30px; padding: 5px; text-align: left; line-height: 36px; font-size: 30px; color: #FFFFFF; ">
        <span style="background-color: rgba(0, 0, 0, 0.7); padding: 0.5px;">
          {{ str_limit(strip_tags($Post->contents), 45) }}
        </span>
        <br>
        <a href="{{ route('category.article.show', [$Category->slug, $Post->slug]) }}" class="btn btn-primary">Baca Selanjutnya</a>
      </div>
    </div>
    @endforeach
    @if(count($Posts) == 0)
    <div>
      <img u="image" src="{{ route('images', 'noImage.png') }}" alt="Belum ada artikel" />
    </div>
    @endif
  </div>

  <!--#region Bullet Navigator Skin Begin -->
  <!-- Help: http://www.jssor.com/development/slider-with-bullet-navigator-jquery.html -->
  <!-- bullet navigator container -->
  <div u="navigator" class="jssorb12" style="bottom: 16px; right: 6px;">
    <!-- bullet navigator item prototype -->
    <div u="prototype"></div>
  </div>
  <!--#endregion Bullet Navigator Skin End -->

  <!--#region Arrow Navigator Skin Begin -->
  <!-- Help: http://www.jssor.com/development/slider-with-arrow-navigator-jquery.html -->
  <!-- Arrow Left -->
  <span u="arrowleft" class="jssora12l" style="top: 123px; left: 0px;">
  </span>
  <!-- Arrow Right -->
  <span u="arrowright" class="jssora12r" style="top: 123px; right: 0px;">
  </span>
  <!--#endregion Arrow Navigator Skin End -->
</div>
<!-- Slider End -->

resources/views/user/layouts/facebook-meta.blade.php
<!-- Facebook Graph API -->
<meta property="og:sitename"      content="Website Desa Mliwang" />
<meta property="og:locale"        content="id_ID" />
@if($fURL)
<meta property="og:url"           content="{{ $fURL }}" />
@endif
@if($fType)
<meta property="og:type"          content="{{ $fType }}" />
@endif
@if($fTitle)
<meta property="og:title"         content="{{ $fTitle }}" />
@endif
@if($fDescription)
<meta property="og:description"   content="{{ str_limit(strip_tags($fDescription), 140) }}" />
@endif
@if($fImage)
<meta property="og:image"         content="{{ route('images', $fImage) }}" />
@else
<meta property="og:image"         content="{{ asset('assets/img/logo2.png') }}" />
@endif

resources/views/user/layouts/navbar.blade.php
  <!-- Navigation Bar Begin -->
  <nav class="navbar">
    <div class="container menubar">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar" style="background-color:white;"></span>
          <span class="icon-bar" style="background-color:white;"></span>
          <span class="icon-bar" style="background-color:white;"></span>
        </button>
        <a class="navbar-brand" href="{{ route('root') }}"><img class="logo img-responsive" src="{{ asset('assets/img/logo2.png') }}" alt="Mliwang" />
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="menu-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{{ route('root') }}" class="menu-cast">Beranda</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle menu-cast" data-toggle="dropdown">
              Artikel Desa<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <?php $CateCount = count($Categories); ?>
              @for($i = 0;($i < $CateCount) && ($i < 10); $i++)
                <li><a href="{{ route('category.show', $Categories[$i]->slug) }}">{{ $Categories[$i]->name }}</a></li>
              @endfor
              @if($CateCount > 10)
                <li class="text-center"><a href="{{ route('category.index') }}"><strong>Selanjutnya</strong></a></li>
              @endif
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle menu-cast" data-toggle="dropdown">
              Potensi Desa<span class="caret"></span></a>
            </a>
            <ul class="dropdown-menu">
              <?php $CataCount = count($Catalogs); ?>
              @for($i = 0;($i < $CataCount) && ($i < 10); $i++)
                <li><a href="{{ route('catalog.show', $Catalogs[$i]->slug) }}">{{ $Catalogs[$i]->name }}</a></li>
              @endfor
              @if($CataCount > 10)
                <li class="text-center"><a href="{{ route('catalog.index') }}"><strong>Selanjutnya</strong></a></li>
              @endif
            </ul>
          </li>
          <li><a href="{{ route('producer.index') }}" class="menu-cast">Profesi</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle menu-cast" data-toggle="dropdown">
              Tentang Mliwang<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="{{ route('about.index') }}">Profil Desa</a>
              </li>
              <li>
                <a href="{{ route('about.map') }}">Peta Desa</a>
              </li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <!-- Navigation Bar End -->

resources/views/user/layouts/sharejs.blade.php
<script src="{{ asset('assets/js/share.js') }}" async defer></script>
<script src="{{ asset('https://apis.google.com/js/platform.js') }}" async defer></script>

resources/views/user/layouts/sidebar.blade.php
<div class="col-md-3 hidden-sm hidden-xs">
  <h2>Navigasi</h2>
  <hr>
  <form action="{{ route('search') }}" method="post" class="form-horizontal">
    <legend>Pencarian</legend>
    <div class="input-group">
      <input class="form-control" type="text" name="term" placeholder="Search">
      <div class="input-group-btn">
        <button type="submit" class="btn btn-default">
          &nbsp<span class="glyphicon glyphicon-search"></span>
        </button>
      </div>
    </div>
    {!! csrf_field() !!}
  </form>
  <br>
  @if(count($LArticles) > 0)
  <legend>Artikel Terbaru</legend>
    @foreach($LArticles as $Article)
    <div class="row sidebar-post">
      <div class="col-md-12">
        <a href="{{ route('category.article.show', [$Article->Category->slug, $Article->slug]) }}">
          <strong>{{ Illuminate\Support\Str::words($Article->title, 3) }}</strong>
        </a>
        <br>
        {{ Illuminate\Support\Str::words(strip_tags($Article->contents), 9) }}
      </div>
    </div>
    @endforeach
  @endif
  @if(count($LProducts) > 0)
  <legend>Potensi Desa Terbaru</legend>
    @foreach($LProducts as $Product)
    <div class="row sidebar-post">
      <div class="col-md-4">
        <a href="{{ route('catalog.product.show', [$Product->Catalog->slug, $Product->slug]) }}">
          @if($Product->Image->first() != null)
          <img src="{{ route('images', $Product->Image->first()->image_path) }}" alt="{{ $Product->Image->first()->description }}" class="img-responsive center-block sidebar-post-image"/>
          @else
          <img src="{{ route('images', 'noImage.png') }}" alt="{{ $Product->title }}" class="img-responsive center-block sidebar-post-image"/>
          @endif
        </a>
      </div>
      <div class="col-md-8">
        <a href="{{ route('catalog.product.show', [$Product->Catalog->slug, $Product->slug]) }}">
          <strong>{{ Illuminate\Support\Str::words($Product->name, 3) }}</strong>
        </a>
        <br>
        {{ Illuminate\Support\Str::words(strip_tags($Product->description), 9) }}
      </div>
    </div>
    @endforeach
  @endif
  <legend>Media Sosial dan Kontak</legend>
  <div class="row text-center">
    <div class="col-md-12">
      <a href="{{ config('pringgolayan.social.youtube.url') }}" target="_blank" title="{{ config('pringgolayan.social.youtube.name') }}"><i class="fa fa-youtube fa-3x"></i></a>
      <a href="mailto:{{ config('pringgolayan.social.email.url') }}" target="_blank" title="{{ config('pringgolayan.social.email.name') }}"><i class="fa fa-envelope-o fa-3x"></i></a>
      <a href="{{ config('pringgolayan.social.facebook.url') }}" target="_blank" title="{{ config('pringgolayan.social.facebook.name') }}"><i class="fa fa-facebook-square fa-3x"></i></a>
      <a href="{{ config('pringgolayan.social.twitter.url') }}" target="_blank" title="{{ config('pringgolayan.social.twitter.name') }}"><i class="fa fa-twitter fa-3x"></i></a>
      <a href="{{ config('pringgolayan.social.instagram.url') }}" target="_blank" title="{{ config('pringgolayan.social.instagram.name') }}"><i class="fa fa-instagram fa-3x"></i></a>
      <a href="{{ config('pringgolayan.social.location.url') }}" target="_blank" title="{{ config('pringgolayan.social.location.name') }}"><i class="fa fa-globe fa-3x"></i></a>
    </div>
  </div>
  <br>
  <div class="row text-center">
    <div class="col-md-12">
      <i class="fa fa-phone fa-lg"></i> :  <strong>{{ config('pringgolayan.social.phone_1.number') }}</strong> ({{ config('pringgolayan.social.phone_1.name') }})
    </div>
  </div>
  <div class="row text-center">
    <div class="col-md-12">
      <i class="fa fa-phone fa-lg"></i> :  <strong>{{ config('pringgolayan.social.phone_2.number') }}</strong> ({{ config('pringgolayan.social.phone_2.name') }})
    </div>
  </div>
</div>