app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Testing Controller
Route::get('test', 'TestingController@index');

//Sitemap Controllers
Route::get('sitemap.xml', [
  //sitemap xml index
  'as'   => 'sitemap.root',
  'uses' => 'User\SitemapController@IndexXML'
  ]);
Route::get('category/sitemap.xml', [
  'as'   => 'sitemap.category',
  'uses' => 'User\SitemapController@CategoryXML'
  ]);
Route::get('catalog/sitemap.xml', [
  'as'   => 'sitemap.catalog',
  'uses' => 'User\SitemapController@CatalogXML'
  ]);
Route::get('about/sitemap.xml', [
  'as'   => 'sitemap.about',
  'uses' => 'User\SitemapController@AboutXML'
  ]);
Route::get('producer/sitemap.xml', [
  'as'   => 'sitemap.producer',
  'uses' => 'User\SitemapController@ProducerXML'
  ]);
Route::get('images/sitemap.xml', [
  'as'   => 'sitemap.image',
  'uses' => 'User\SitemapController@ImageXML'
  ]);

//Common Controllers
Route::get('images/{path}', [
  'as'   => 'images',
  'uses' => 'Common\ImageController@respond'
  ]);

//AJAXs
Route::get('images/', [
  'as'   => 'ajax.images.list',
  'uses' => 'Common\ImageController@jsonList'
  ]);
Route::get('products/', [
  'as'   => 'ajax.product.list',
  'uses' => 'Common\ProductController@jsonList'
  ]);

//FrontEnd Controllers
Route::get('/', [
  'as'   => 'root',
  'uses' => 'User\HomeController@index'
  ]);
Route::post('search/', [
  'as'   => 'search',
  'uses' => 'User\SearchController@index'
  ]);
Route::resource('category', 'User\ArticleCategoryController',[
  'only' => ['index', 'show']
  ]);
Route::resource('category.article', 'User\ArticleController', [
  'only' => ['index', 'show']
  ]);
Route::resource('catalog', 'User\ProductCategoryController', [
  'only' => ['index', 'show']
  ]);
Route::resource('catalog.product', 'User\ProductController', [
  'only' => ['index', 'show']
  ]);
Route::get('about/map', [
  'as'   => 'about.map',
  'uses' => 'User\AboutController@showMap'
  ]);
Route::resource('about', 'User\AboutController', [
  'only' => ['index']
  ]);
Route::resource('producer', 'User\ProducerController', [
  'only' => ['index', 'show']
  ]);

//Reset Password Controllers (accessible by victim)
  // Password reset routes...
  Route::get('password/reset/{token}', [
    'as'  => 'password.reset.token',
    'uses'=> 'Auth\PasswordController@getReset'
  ]);
  Route::post('password/reset', [
    'as'  => 'password.reset.post',
    'uses'=> 'Auth\PasswordController@postReset'
  ]);

//BackEnd Controllers (administrators)
Route::get('admin', [
  'as'   => 'admin.root',
  'uses' => 'Admin\UAuthController@home'
]);
Route::post('admin',[
  'as'   => 'admin.login',
  'uses' => 'Admin\UAuthController@login'
]);
Route::group(['middleware' => 'auth'], function(){
  Route::get('admin/logout',[
    'as'   => 'admin.logout',
    'uses' => 'Admin\UAuthController@logout'
  ]);
  //User Password Reset Controllers
    // Password reset link request routes...
    Route::get('admin/password/email', [
      'as'   => 'admin.password.reset',
      'uses' => 'Auth\PasswordController@getEmail'
    ]);
    Route::post('admin/password/email', [
      'as'   => 'admin.password.reset.post',
      'uses' => 'Auth\PasswordController@postEmail'
    ]);


  //Search Controller hooks
  Route::any('admin/category/search', [
    'as'    => 'admin.category.search',
    'uses'  => 'Admin\ArticleCategoryController@search'
  ]);
  Route::any('admin/catalog/search', [
    'as'    => 'admin.catalog.search',
    'uses'  => 'Admin\ProductCategoryController@search'
  ]);
  Route::any('admin/article/search', [
    'as'    => 'admin.article.search',
    'uses'  => 'Admin\ArticleController@search'
  ]);
  Route::any('admin/product/search', [
    'as'    => 'admin.product.search',
    'uses'  => 'Admin\ProductController@search'
  ]);
  Route::any('admin/user/search', [
    'as'    => 'admin.user.search',
    'uses'  => 'Admin\UserController@search'
  ]);
  Route::any('admin/image/search', [
    'as'    => 'admin.image.search',
    'uses'  => 'Admin\ImageController@search'
  ]);
  Route::any('admin/producer/search', [
    'as'    => 'admin.producer.search',
    'uses'  => 'Admin\ProducerController@search'
  ]);

  //Management Controllers
  Route::resource('admin/category', 'Admin\ArticleCategoryController', [

  ]);
  Route::resource('admin/article', 'Admin\ArticleController', [
    'except' => ['show']
  ]);
  Route::resource('admin/catalog', 'Admin\ProductCategoryController', [

  ]);
  Route::resource('admin/product', 'Admin\ProductController', [
    'except' => ['show']
  ]);
  Route::resource('admin/image', 'Admin\ImageController', [
    'only'   => ['index', 'store', 'update', 'destroy']
  ]);
  Route::resource('admin/authorities', 'Admin\AuthoritiesController',[
    'only'   => ['index', 'store', 'update', 'destroy']
  ]);
  Route::resource('admin/demographics', 'Admin\DemographicController', [
    'only'   => ['index', 'store', 'update', 'destroy']
  ]);
  Route::resource('admin/user', 'Admin\UserController',[
    'except' => ['destroy']
  ]);
  Route::resource('admin/producer', 'Admin\ProducerController', [
    'except' => ['show']
  ]);

});

resources/views/admin/beranda.blade.php
@extends('admin.layouts.master')
@section('meta') @endsection
@section('title') Beranda @endsection
@section('css') @endsection
@section('js') @endsection
@section('contents')
  <strong>Selamat Datang</strong>, {{ $lUser->realname }} (<i>{{ $lUser->username }}</i>)
  <br>
  Pada administrasi website Desa Mliwang.
@endsection
@section('pagination') @endsection

resources/views/admin/citra.blade.php
@extends('admin.layouts.master')
@section('meta') @endsection
@section('title') Manajemen Citra @endsection
@section('css') @endsection
@section('js') @endsection
@section('contents')

<!-- Flash Data -->
@include('common.layouts.form-alerter')
@include('common.layouts.form-success')

<div class="row">
  <div class="col-md-6">
    <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#tambahGambar">Tambah Gambar</a>
  </div>
  <div class="col-md-6">
    <?php $searchURL = route('admin.image.search') ?>
      <form class="form-horizontal" action="{{ $searchURL }}" method="post">
        <div class="input-group">
          <input type="text" name="term" class="form-control">
          <div class="input-group-btn">
            <button type="submit" class="btn btn-default">
              &nbsp<span class="glyphicon glyphicon-search"></span>
            </button>
          </div>
        </div>
        {!! csrf_field() !!}
      </form>
  </div>
</div>

<hr>

<div class="modal fade" id="tambahGambar" tabindex="-1" role="dialog" aria-labelledby="tambahGambarLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="tambahGambarLabel">Tambah Gambar</h4>
      </div>
      <div class="modal-body">
        <form class="" action="{{ route('admin.image.store') }}" method="post" enctype="multipart/form-data">
          {!! csrf_field() !!}
          <div class="form-group">
            <label for="nama">Nama Gambar</label>
            <input type="text" class="form-control" name="name" id="nama" placeholder="Nama Gambar" required>
          </div>
          <div class="form-group">
            <label for="deskripsi">Deskripsi</label>
            <textarea id="deskripsi" name="description" class="form-control" name="deskripsi" rows="8" cols="40" placeholder="Deskripsi Gambar"></textarea>
          </div>
          <div class="form-group">
            <label for="gambar">File <small>(maks. 2 MB dan resolusi 1500px x 1500px)</small></label>
            <input type="file" accept="image/*" name="file" id="gambar" required>
          </div>
          <hr>
          <div class="text-right">
            <input type="submit" value="Simpan" class="btn btn-success">
            <input type="reset" value="Batal" class="btn btn-danger" data-dismiss="modal">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="media">
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  @foreach($Images as $Image)
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="heading{{ $Image->id }}">
        <a href="#collapse{{ $Image->id }}" role="button" data-toggle="collapse" data-parent="#accordion" aria-expanded="true" aria-controls="collapse{{ $Image->id }}">
          <h4 class="panel-title">
            {{ $Image->name }}
          </h4>
        </a>
      </div>
      <div id="collapse{{ $Image->id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ $Image->id }}">
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-hover">
              <colgroup>
                <col span="1" style="width: 30%;"></col>
                <col span="1" style="width: 70%;"></col>
              </colgroup>
              <tr>
                <td><b>Nama</b></td>
                <td>{{ $Image->name }}</td>
              </tr>
              <tr>
                <td><b>Deskripsi</b></td>
                <td>{{ $Image->description }}</td>
              </tr>
              <tr>
                <td><b>Nama File</b></td>
                <td>{{ $Image->image_path }}</td>
              </tr>
              <tr>
                <td><b>URL</b></td>
                <td><a href="{{ route('images', $Image->image_path) }}" target="_blank">{{ route('images', $Image->image_path) }}</a></td>
              </tr>
              <tr>
                <td><b>MIME</b></td>
                <td>{{ $Image->mime }}</td>
              </tr>
              {{--<tr>
                <td><b>Ukuran Gambar (lebar x tinggi)</b></td>
                <td>{{ $Image->width }} x {{ $Image->height }}</td>
              </tr>--}}
              <tr>
                <td><b>Ukuran File (Kbyte)</b></td>
                <td>{{ ceil($Image->filesize/1024) }}</td>
              </tr>
              <tr>
                <td><b>Ditambahkan pada</b></td>
                <td>{{ $Image->created_at->format('D, d-m-Y') }}</td>
              </tr>
              <tr>
                <td><b>Diperbarui pada</b></td>
                <td>{{ $Image->updated_at->format('D, d-m-Y') }}</td>
              </tr>
            </table>
            <div class="text-right">
              <a href="#" class="btn btn-default" data-toggle="modal" data-target="#editGambar{{ $Image->id }}">Sunting Rincian</a>
              <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#hapusGambar{{ $Image->id }}">Hapus</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="editGambar{{ $Image->id }}" tabindex="-1" role="dialog" aria-labelledby="suntingGambarLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="suntingGambarLabel">Sunting Gambar</h4>
          </div>
          <div class="modal-body">
            <form class="" action="{{ route('admin.image.update', $Image->id) }}" method="post" enctype="multipart/form-data">
              {!! csrf_field() !!}
              {!! method_field('put') !!}
              <div class="form-group">
                <label for="nama">Nama Gambar</label>
                <input type="text" class="form-control" name="name" id="nama" placeholder="Nama Gambar" value="{{ $Image->name }}" required>
              </div>
              <div class="form-group">
                <label for="deskripsi">Deskripsi</label>
                <textarea id="deskripsi" name="description" class="form-control" name="deskripsi" rows="8" cols="40" placeholder="Deskripsi Gambar">{{ $Image->description }}</textarea>
              </div>
              <div class="form-group">
                <label for="gambar">File(maks. 2 MB dan resolusi 1500px x 1500px)</label>
                <input type="file" accept="image/*" name="file" id="gambar">
              </div>
              <hr>
              <div class="text-right">
                <input type="submit" value="Simpan" class="btn btn-success">
                <input type="reset" value="Batal" class="btn btn-danger" data-dismiss="modal">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="hapusGambar{{ $Image->id }}" tabindex="-1" role="dialog" aria-labelledby="hapusGambarLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="suntingGambarLabel">Hapus Gambar</h4>
          </div>
          <div class="modal-body">
            <p>
              Apakah anda yakin ingin menghapus <strong>{{ $Image->name }}</strong> ({{ $Image->image_path }})
            </p>
          </div>
          <div class="modal-footer">
            <form class="" action="{{ route('admin.image.destroy', $Image->id) }}" method="post">
              {!! csrf_field() !!}
              {!! method_field('delete') !!}
              <input type="submit" value="Hapus" class="btn btn-danger">
              <input type="reset"  value="Batal" class="btn btn-default" data-dismiss="modal">
            </form>
          </div>
        </div>
      </div>
    </div>
  @endforeach
  </div>
</div>
@endsection
@section('pagination') {!! $Images->render() !!} @endsection

resources/views/admin/daftar-artikel.blade.php
@extends('admin.layouts.master')
@section('meta') @endsection
@section('title') Artikel @endsection
@section('css') @endsection
@section('js') @endsection
@section('contents')

<?php $searchURL = route('admin.article.search'); ?>
@include('admin.layouts.search')

<!-- Flash Data -->
@include('common.layouts.form-alerter')
@include('common.layouts.form-success')

<div class="table-responsive">
  <table class="table table-hover">
    <colgroup>
      <col span="1" style="width: 5%;"></col>
      <col span="1" style="width: 45%;"></col>
      <col span="1" style="width: 20%"></col>
      <col span="1" style="width: 20%"></col>
      <col span="1" style="width: 5%;"></col>
      <col span="1" style="width: 5%;"></col>
    </colgroup>
    <tr>
      <th>No</th>
      <th>Judul Artikel</th>
      <th>Kategori</th>
      <th>Penyunting Terakhir</th>
      <th></th>
      <th></th>
    </tr>
    <?php $iCounter = 1 ?>
    @foreach($Posts as $Post)
    <tr>
      <td>{{ $iCounter++ }}</td>
      <td><a href="{{ route('category.article.show', [$Post->Category->slug, $Post->slug]) }}" target="_blank">{{ $Post->title }}</a></td>
      <td><a href="{{ route('admin.category.show', $Post->Category->id) }}">{{ $Post->Category->name }}</a></td>
      <td>{{ $Post->User->realname }}</td>
      <td><a class="btn btn-default" href="{{ route('admin.article.edit', $Post->id) }}">Sunting</a></td>
      <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirmation{{ $Post->id }}">Hapus</a></td>
    </tr>
    @endforeach
  </table>
</div>
<!-- Modal -->
@foreach($Posts as $Post)
<div class="modal fade" id="confirmation{{ $Post->id }}" tabindex="-1" role="dialog" aria-labelledby="confirmationLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="confirmationLabel">Konfirmasi</h4>
      </div>
      <div class="modal-body">
        <p>Apakah anda yakin ingin menghapus artikel <strong>{{$Post->title}}</strong>?</p>
      </div>
      <div class="modal-footer">
        <form action="{{ route('admin.article.destroy', $Post->id) }}" method="post">
          {!! csrf_field() !!}
          {!! method_field('delete') !!}
          <input type="submit" value="Hapus" class="btn btn-danger">
          <input type="reset"  value="Batal" class="btn btn-default" data-dismiss="modal">
        </form>
      </div>
    </div>
  </div>
</div>
@endforeach
@endsection
@section('pagination') {!! $Posts->render() !!} @endsection

resources/views/admin/daftar-katalog.blade.php
@extends('admin.layouts.master')
@section('meta') @endsection
@section('title') Katalog @endsection
@section('css') @endsection
@section('js') @endsection
@section('contents')

<?php $searchURL = route('admin.catalog.search'); ?>
@include('admin.layouts.search')

<!-- Flash Data -->
@include('common.layouts.form-alerter')
@include('common.layouts.form-success')

<div class="table-responsive">
  <table class="table table-hover">
    <colgroup>
      <col span="1" style="width: 5%;"></col>
      <col span="1" style="width: 45%;"></col>
      <col span="1" style="width: 40%"></col>
      <col span="1" style="width: 5%;"></col>
      <col span="1" style="width: 5%;"></col>
    </colgroup>
    <tr>
      <th>No</th>
      <th>Katalog</th>
      <th>Jumlah Produk</th>
      <th></th>
      <th></th>
    </tr>
    <?php $iCounter = 1 ?>
    @foreach($Catalogs as $Catalog)
    <tr>
      <td>{{ $iCounter++ }}</td>
      <td><a href="{{ route('admin.catalog.show', $Catalog->id) }}">{{ $Catalog->name }}</a></td>
      <td>{{ count($Catalog->Product) }}</td>
      <td><a class="btn btn-default" href="{{ route('admin.catalog.edit', $Catalog->id) }}">Sunting</a></td>
      <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirmation{{ $Catalog->id }}">Hapus</a></td>
    </tr>
    @endforeach
  </table>
</div>
<!-- Modal -->
@foreach($Catalogs as $Catalog)
<div class="modal fade" id="confirmation{{ $Catalog->id }}" tabindex="-1" role="dialog" aria-labelledby="confirmationLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="confirmationLabel">Konfirmasi</h4>
      </div>
      <div class="modal-body">
        <p>Apakah anda yakin ingin menghapus katalog <strong>{{$Catalog->name}}</strong>?</p>
        <p>Sejumlah {{ count($Catalog->Product) }} produk juga akan <strong>terhapus secara permanen</strong>!</p>
      </div>
      <div class="modal-footer">
        <form action="{{ route('admin.catalog.destroy', $Catalog->id) }}" method="post">
          {!! csrf_field() !!}
          {!! method_field('delete') !!}
          <input type="submit" value="Hapus" class="btn btn-danger">
          <input type="reset"  value="Batal" class="btn btn-default" data-dismiss="modal">
        </form>
      </div>
    </div>
  </div>
</div>
@endforeach
@endsection
@section('pagination') {!! $Catalogs->render() !!} @endsection

resources/views/admin/daftar-kategori.blade.php
@extends('admin.layouts.master')
@section('meta') @endsection
@section('title') Kategori @endsection
@section('css') @endsection
@section('js') @endsection
@section('contents')

<?php $searchURL = route('admin.category.search'); ?>
@include('admin.layouts.search')

<!-- Flash Data -->
@include('common.layouts.form-alerter')
@include('common.layouts.form-success')

<div class="table-responsive">
  <table class="table table-hover">
    <colgroup>
      <col span="1" style="width: 5%;"></col>
      <col span="1" style="width: 30%;"></col>
      <col span="1" style="width: 25%"></col>
      <col span="1" style="width: 30%"></col>
      <col span="1" style="width: 5%;"></col>
      <col span="1" style="width: 5%;"></col>
    </colgroup>
    <tr>
      <th>No</th>
      <th>Kategori</th>
      <th class="text-center">Jumlah Artikel</th>
      <th class="text-center">Halaman Utama</th>
      <th></th>
      <th></th>
    </tr>
    <?php $iCounter = 1 ?>
    @foreach($Categories as $Category)
    <tr>
      <td>{{ $iCounter++ }}</td>
      <td><a href="{{ route('admin.category.show', $Category->id) }}">{{ $Category->name }}</a></td>
      <td class="text-center">{{ count($Category->Article) }}</td>
      <td class="text-center">@if($Category->featured == 1)<span class="fa fa-check fa-fw"></span>@endif</td>
      <td><a class="btn btn-default" href="{{ route('admin.category.edit', $Category->id) }}">Sunting</a></td>
      <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirmation{{ $Category->id }}">Hapus</a></td>
    </tr>
    @endforeach
  </table>
</div>
<!-- Modal -->
@foreach($Categories as $Category)
<div class="modal fade" id="confirmation{{ $Category->id }}" tabindex="-1" role="dialog" aria-labelledby="confirmationLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="confirmationLabel">Konfirmasi</h4>
      </div>
      <div class="modal-body">
        <p>Apakah anda yakin ingin menghapus artikel <strong>{{ $Category->name }}</strong>?</p>
        <p>Sejumlah {{ count($Category->Article) }} artikel juga akan <strong>terhapus secara permanen</strong>!</p>
      </div>
      <div class="modal-footer">
        <form action="{{ route('admin.category.destroy', $Category->id) }}" method="post">
          {!! csrf_field() !!}
          {!! method_field('delete') !!}
          <input type="submit" value="Hapus" class="btn btn-danger">
          <input type="reset"  value="Batal" class="btn btn-default" data-dismiss="modal">
        </form>
      </div>
    </div>
  </div>
</div>
@endforeach
@endsection
@section('pagination') {!! $Categories->render() !!} @endsection

resources/views/admin/daftar-produk.blade.php
@extends('admin.layouts.master')
@section('meta') @endsection
@section('title') Potensi Desa @endsection
@section('css') @endsection
@section('js') @endsection
@section('contents')

<?php $searchURL = route('admin.product.search'); ?>
@include('admin.layouts.search')

<!-- Flash Data -->
@include('common.layouts.form-alerter')
@include('common.layouts.form-success')

<div class="table-responsive">
  <table class="table table-hover">
    <colgroup>
      <col span="1" style="width: 5%;"></col>
      <col span="1" style="width: 45%;"></col>
      <col span="1" style="width: 40%"></col>
      <col span="1" style="width: 5%;"></col>
      <col span="1" style="width: 5%;"></col>
    </colgroup>
    <tr>
      <th>No</th>
      <th>Nama Produk</th>
      <th>Katalog</th>
      <th></th>
      <th></th>
    </tr>
    <?php $iCounter = 1 ?>
    @foreach($Products as $Product)
    <tr>
      <td>{{ $iCounter++ }}</td>
      <td><a href="{{ route('catalog.product.show', [$Product->Catalog->slug, $Product->slug]) }}" target="_blank">{{ $Product->name }}</a></td>
      <td><a href="{{ route('admin.catalog.show', $Product->Catalog->id) }}">{{ $Product->Catalog->name }}</a></td>
      <td><a class="btn btn-default" href="{{ route('admin.product.edit', $Product->id) }}">Sunting</a></td>
      <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirmation{{ $Product->id }}">Hapus</a></td>
    </tr>
    @endforeach
  </table>
</div>
<!-- Modal -->
@foreach($Products as $Product)
<div class="modal fade" id="confirmation{{ $Product->id }}" tabindex="-1" role="dialog" aria-labelledby="confirmationLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="confirmationLabel">Konfirmasi</h4>
      </div>
      <div class="modal-body">
        <p>Apakah anda yakin ingin menghapus produk <strong>{{$Product->name}}</strong>?</p>
      </div>
      <div class="modal-footer">
        <form action="{{ route('admin.product.destroy', $Product->id) }}" method="post">
          {!! csrf_field() !!}
          {!! method_field('delete') !!}
          <input type="submit" value="Hapus" class="btn btn-danger">
          <input type="reset"  value="Batal" class="btn btn-default" data-dismiss="modal">
        </form>
      </div>
    </div>
  </div>
</div>
@endforeach
@endsection
@section('pagination') {!! $Products->render() !!} @endsection

resources/views/admin/daftar-produsen.blade.php
@extends('admin.layouts.master')
@section('meta') @endsection
@section('title') Profesi @endsection
@section('css') @endsection
@section('js') @endsection
@section('contents')

<?php $searchURL = route('admin.producer.search'); ?>
@include('admin.layouts.search')

<!-- Flash Data -->
@include('common.layouts.form-alerter')
@include('common.layouts.form-success')
<table class="table table-hover">
  <colgroup>
    <col span="1" style="width: 5%;"></col>
    <col span="1" style="width: 20%;"></col>
    <col span="1" style="width: 45%"></col>
    <col span="1" style="width: 20%"></col>
    <col span="1" style="width: 5%;"></col>
    <col span="1" style="width: 5%;"></col>
  </colgroup>
  <tr>
    <th>No</th>
    <th>Nama</th>
    <th>Alamat</th>
    <th>Kontak</th>
    <th></th>
    <th></th>
  </tr>
  <?php $iCounter = 1 ?>
  @foreach($Producers as $Producer)
  <tr>
    <td>{{ $iCounter++ }}</td>
    <td><a href="{{ route('producer.show', $Producer->slug) }}" target="_blank">{{ $Producer->name }}</a></td>
    <td>{{ $Producer->address }}</td>
    <td>{{ $Producer->contact }}</td>
    <td><a href="{{ route('admin.producer.edit', [$Producer->id]) }}" class="btn btn-default">Sunting</a></td>
    <td><a href="#" class="btn btn-danger" data-toggle="modal" data-target="#hapusProdusen{{ $Producer->id }}">Hapus</a></td>
  </tr>
  @endforeach
</table>

@foreach($Producers as $Producer)
<div class="modal fade" id="hapusProdusen{{ $Producer->id }}" tabindex="-1" role="dialog" aria-labelledby="hapusProdusenLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="hapusProdusenLabel">Hapus Produsen</h4>
      </div>
      <div class="modal-body">
        <p>Apakah anda yakin ingin menghapus <strong>{{$Producer->name}}</strong> ({{ str_limit($Producer->address, 100) }}) dari daftar produsen?</p>
      </div>
      <div class="modal-footer">
        <form action="{{ route('admin.producer.destroy', $Producer->id) }}" method="post">
          {!! csrf_field() !!}
          {!! method_field('delete') !!}
          <input type="submit" value="Hapus" class="btn btn-danger">
          <input type="reset"  value="Batal" class="btn btn-default" data-dismiss="modal">
        </form>
      </div>
    </div>
  </div>
</div>
@endforeach

@endsection
@section('pagination') {!! $Producers->render() !!} @endsection