app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Testing Controller
Route::get('test', 'TestingController@index');

//Sitemap Controllers
Route::get('sitemap.xml', [
  //sitemap xml index
  'as'   => 'sitemap.root',
  'uses' => 'User\SitemapController@IndexXML'
  ]);
Route::get('category/sitemap.xml', [
  'as'   => 'sitemap.category',
  'uses' => 'User\SitemapController@CategoryXML'
  ]);
Route::get('catalog/sitemap.xml', [
  'as'   => 'sitemap.catalog',
  'uses' => 'User\SitemapController@CatalogXML'
  ]);
Route::get('about/sitemap.xml', [
  'as'   => 'sitemap.about',
  'uses' => 'User\SitemapController@AboutXML'
  ]);
Route::get('producer/sitemap.xml', [
  'as'   => 'sitemap.producer',
  'uses' => 'User\SitemapController@ProducerXML'
  ]);
Route::get('images/sitemap.xml', [
  'as'   => 'sitemap.image',
  'uses' => 'User\SitemapController@ImageXML'
  ]);

//Common Controllers
Route::get('images/{path}', [
  'as'   => 'images',
  'uses' => 'Common\ImageController@respond'
  ]);

//AJAXs
Route::get('images/', [
  'as'   => 'ajax.images.list',
  'uses' => 'Common\ImageController@jsonList'
  ]);
Route::get('products/', [
  'as'   => 'ajax.product.list',
  'uses' => 'Common\ProductController@jsonList'
  ]);

//FrontEnd Controllers
Route::get('/', [
  'as'   => 'root',
  'uses' => 'User\HomeController@index'
  ]);
Route::post('search/', [
  'as'   => 'search',
  'uses' => 'User\SearchController@index'
  ]);
Route::resource('category', 'User\ArticleCategoryController',[
  'only' => ['index', 'show']
  ]);
Route::resource('category.article', 'User\ArticleController', [
  'only' => ['index', 'show']
  ]);
Route::resource('catalog', 'User\ProductCategoryController', [
  'only' => ['index', 'show']
  ]);
Route::resource('catalog.product', 'User\ProductController', [
  'only' => ['index', 'show']
  ]);
Route::get('about/map', [
  'as'   => 'about.map',
  'uses' => 'User\AboutController@showMap'
  ]);
Route::resource('about', 'User\AboutController', [
  'only' => ['index']
  ]);
Route::resource('producer', 'User\ProducerController', [
  'only' => ['index', 'show']
  ]);

//Reset Password Controllers (accessible by victim)
  // Password reset routes...
  Route::get('password/reset/{token}', [
    'as'  => 'password.reset.token',
    'uses'=> 'Auth\PasswordController@getReset'
  ]);
  Route::post('password/reset', [
    'as'  => 'password.reset.post',
    'uses'=> 'Auth\PasswordController@postReset'
  ]);

//BackEnd Controllers (administrators)
Route::get('admin', [
  'as'   => 'admin.root',
  'uses' => 'Admin\UAuthController@home'
]);
Route::post('admin',[
  'as'   => 'admin.login',
  'uses' => 'Admin\UAuthController@login'
]);
Route::group(['middleware' => 'auth'], function(){
  Route::get('admin/logout',[
    'as'   => 'admin.logout',
    'uses' => 'Admin\UAuthController@logout'
  ]);
  //User Password Reset Controllers
    // Password reset link request routes...
    Route::get('admin/password/email', [
      'as'   => 'admin.password.reset',
      'uses' => 'Auth\PasswordController@getEmail'
    ]);
    Route::post('admin/password/email', [
      'as'   => 'admin.password.reset.post',
      'uses' => 'Auth\PasswordController@postEmail'
    ]);


  //Search Controller hooks
  Route::any('admin/category/search', [
    'as'    => 'admin.category.search',
    'uses'  => 'Admin\ArticleCategoryController@search'
  ]);
  Route::any('admin/catalog/search', [
    'as'    => 'admin.catalog.search',
    'uses'  => 'Admin\ProductCategoryController@search'
  ]);
  Route::any('admin/article/search', [
    'as'    => 'admin.article.search',
    'uses'  => 'Admin\ArticleController@search'
  ]);
  Route::any('admin/product/search', [
    'as'    => 'admin.product.search',
    'uses'  => 'Admin\ProductController@search'
  ]);
  Route::any('admin/user/search', [
    'as'    => 'admin.user.search',
    'uses'  => 'Admin\UserController@search'
  ]);
  Route::any('admin/image/search', [
    'as'    => 'admin.image.search',
    'uses'  => 'Admin\ImageController@search'
  ]);
  Route::any('admin/producer/search', [
    'as'    => 'admin.producer.search',
    'uses'  => 'Admin\ProducerController@search'
  ]);

  //Management Controllers
  Route::resource('admin/category', 'Admin\ArticleCategoryController', [

  ]);
  Route::resource('admin/article', 'Admin\ArticleController', [
    'except' => ['show']
  ]);
  Route::resource('admin/catalog', 'Admin\ProductCategoryController', [

  ]);
  Route::resource('admin/product', 'Admin\ProductController', [
    'except' => ['show']
  ]);
  Route::resource('admin/image', 'Admin\ImageController', [
    'only'   => ['index', 'store', 'update', 'destroy']
  ]);
  Route::resource('admin/authorities', 'Admin\AuthoritiesController',[
    'only'   => ['index', 'store', 'update', 'destroy']
  ]);
  Route::resource('admin/demographics', 'Admin\DemographicController', [
    'only'   => ['index', 'store', 'update', 'destroy']
  ]);
  Route::resource('admin/user', 'Admin\UserController',[
    'except' => ['destroy']
  ]);
  Route::resource('admin/producer', 'Admin\ProducerController', [
    'except' => ['show']
  ]);

});

resources/views/admin/layouts/image-refresh.blade.php
<script>
  var fImage = function()
  {
    var b = jQuery.ajax({
      url: "{{ route('ajax.images.list') }}",
      type: "get",
      dataType: "json",
    })
    .done(function(msg){
      var str = "<option value=\"-1\"> - </option>\n";
      for(index = 0; index < msg.length; index++)
      {
        str += "<option value=\"" + msg[index].id + "\">" + msg[index].title + "</option>\n";
      }
      var selected = jQuery("[name='image'], [name='image[]'], [name='intro_image']");
      selected.each(function(){
        var oldValue = $(this).val();
        $(this).html(str).children("[value=" + oldValue + "]").attr("selected", "");
      });
    });
  }
  jQuery("[name='RefreshAndReload']").click(fImage);
  setInterval(fImage, 30000);
</script>
{{-- <button type="button" name="RefreshAndReload" class="btn btn-default"><i class="fa fa-refresh"></i> Muat Ulang Relasi</button> --}}

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="id">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    @section('meta')

    @show
    <title> Mliwang (Administrasi) | @yield('title') </title>
    <!-- Bootstrap -->
    <link href="{{ asset('vendor/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="{{ asset('vendor/metisMenu/dist/metisMenu.min.css') }}" rel="stylesheet">
    <!-- Timeline CSS -->
    <link href="{{ asset('vendor/startbootstrap-sb-admin-2/dist/css/timeline.css') }}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ asset('vendor/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css') }}" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="{{ asset('vendor/morrisjs/morris.css') }}" rel="stylesheet">

    <!-- Common CSS -->
    <link href="{{ asset('assets/img/favicon.png') }}" rel="shortcut icon">
    <link href="{{ asset('assets/css/admin.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    @section('css')

    @show
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top bar-cast" role="navigation" style="margin-bottom: 0">
      <!-- Navigation -->
      @include('admin.layouts.navbar')
      @include('admin.layouts.sidebar')
    </nav>
    <!-- Content Begin -->
    <div id="page-wrapper">
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">@yield('title')</h1>
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <div class="row">
        <div class="col-md-12">
          @section('contents')

          @show
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <nav>
            @section('pagination')

            @show
          </nav>
        </div>
      </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{ asset('vendor/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap3-typeahead/bootstrap3-typeahead.min.js') }}"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{ asset('vendor/metisMenu/dist/metisMenu.min.js') }}"></script>
    <!-- Morris Charts JavaScript -->
    <script src="{{ asset('vendor/raphael/raphael-min.js') }}"></script>
    <script src="{{ asset('vendor/morrisjs/morris.min.js') }}"></script>
    <!-- Custom Theme JavaScript -->
    <script src="{{ asset('vendor/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js') }}"></script>
    @section('js')

    @show
  </body>
</html>

resources/views/admin/layouts/navbar.blade.php
<!-- Navbar -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="color:white;">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar" style="background-color:white;"></span>
    <span class="icon-bar" style="background-color:white;"></span>
    <span class="icon-bar" style="background-color:white;"></span>
  </button>
  <a class="navbar-brand" href="{{ route('admin.root') }}"><img class="logo img-responsive" src="{{ asset('assets/img/logo2.png') }}" alt="Mliwang" /></a>
</div>
<!-- /.navbar-header -->

<ul class="nav navbar-top-links navbar-right">
  <li>
    <a href="{{ route('root') }}" target="_blank"><i class="fa fa-external-link"></i> Lihat Situs</a>
  </li>
  <!-- /.dropdown -->
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="fa fa-user fa-fw"></i> {{ $lUser->realname }} <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
      <li>
        <a href="{{ route('admin.user.show', $lUser->id) }}" class="menu-cast"><i class="fa fa-user fa-fw"></i> User Profile</a>
      </li>
      <li>
        <a href="{{ route('admin.user.edit', $lUser->id) }}" class="menu-cast"><i class="fa fa-gear fa-fw"></i> Settings</a>
      </li>
      <li class="divider"></li>
      <li>
        <a href="{{ route('admin.logout') }}" class="menu-cast"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
      </li>
    </ul>
    <!-- /.dropdown-user -->
  </li>
  <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->

resources/views/admin/layouts/product-refresh.blade.php
<script>
  var fProduct = function()
  {
    var b = jQuery.ajax({
      url: "{{ route('ajax.product.list') }}",
      type: "get",
      dataType: "json",
    })
    .done(function(msg){
      var str = "<option value=\"-1\"> - </option>\n";
      for(index = 0; index < msg.length; index++)
      {
        str += "<option value=\"" + msg[index].id + "\">" + msg[index].name + "</option>\n";
      }
      var selected = jQuery("[name='product[]']");
      selected.each(function(){
        var oldValue = $(this).val();
        $(this).html(str).children("[value=" + oldValue + "]").attr("selected", "");
      });
    });
  }
  jQuery("[name='RefreshAndReload']").click(fProduct);
  setInterval(fProduct, 30000);
</script>
{{-- <button type="button" name="RefreshAndReload" class="btn btn-default"><i class="fa fa-refresh"></i> Muat Ulang Relasi</button> --}}

resources/views/admin/layouts/search.blade.php
<div class="row" style="margin-bottom: 20px">
  <div class="col-md-4 col-md-offset-8 col-sm-6 col-sm-offset-6">
    <form class="form-horizontal" action="{{ $searchURL }}" method="post">
      <div class="input-group">
        <input type="text" name="term" class="form-control">
        <div class="input-group-btn">
          <button type="submit" class="btn btn-default">
            &nbsp<span class="glyphicon glyphicon-search"></span>
          </button>
        </div>
      </div>
      {!! csrf_field() !!}
    </form>
  </div>
</div>

resources/views/admin/layouts/sidebar.blade.php
<!-- Sidebar -->
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <li>
        <a href="#"><i class="fa fa-pencil-square-o fa-fw"></i> Artikel<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="{{ route('admin.category.index') }}">Daftar Kategori</a>
          </li>
          <li>
            <a href="{{ route('admin.category.create') }}">Buat Kategori Baru</a>
          </li>
          <hr class="sidebar-separator">
          <li>
            <a href="{{ route('admin.article.index') }}">Daftar Semua Artikel</a>
          </li>
          <li>
            <a href="{{ route('admin.article.create') }}">Buat Artikel Baru</a>
          </li>
        </ul>
        <!-- /.nav-second-level -->
      </li>
      <li>
        <a href="#"><i class="fa fa-tag fa-fw"></i> Potensi Desa<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="{{ route('admin.catalog.index') }}">Daftar Katalog Potensi Desa</a>
          </li>
          <li>
            <a href="{{ route('admin.catalog.create') }}">Tambah Katalog Potensi Desa</a>
          </li>
          <hr class="sidebar-separator">
          <li>
            <a href="{{ route('admin.product.index') }}">Daftar Potensi Desa</a>
          </li>
          <li>
            <a href="{{ route('admin.product.create') }}">Tambah Potensi Desa Baru</a>
          </li>
          <hr class="sidebar-separator">
          <li>
            <a href="{{ route('admin.producer.index') }}">Data Profesi</a>
          </li>
          <li>
            <a href="{{ route('admin.producer.create') }}">Tambah Profesi</a>
          </li>
        </ul>
        <!-- /.nav-second-level -->
      </li>
      <li>
        <a href="#"><i class="fa fa-play-circle-o fa-fw"></i> Manajemen Multimedia<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="{{ route('admin.image.index') }}">Manajer Citra</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="#"><i class="fa fa-users fa-fw"></i> Pengguna<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="{{ route('admin.user.index') }}">Daftar Pengguna</a>
          </li>
          <li>
            <a href="{{ route('admin.user.create') }}">Daftarkan Pengguna Baru</a>
          </li>
          <li>
            <a href="{{ route('admin.password.reset') }}">Reset Password Pengguna</a>
          </li>
        </ul>
        <!-- /.nav-second-level -->
      </li>
      <li>
        <a href="#"><i class="fa fa-flag fa-fw"></i> Tentang Mliwang<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li>
            <a href="{{ route('admin.authorities.index') }}">Data Pengurus Desa</a>
          </li>
          <li>
            <a href="{{ route('admin.demographics.index') }}">Data Demografi</a>
          </li>
        </ul>
        <!-- /.nav-second-level -->
      </li>
    </ul>
  </div>
  <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

resources/views/admin/layouts/tinymce-script.blade.php
<script src="{{ asset('vendor/tinymce/tinymce.min.js') }}"></script>
<script src="{{ asset('assets/js/tinymce-init.js') }}"></script>
<script>
  tinyMCE_settings.image_list = "{{ route('ajax.images.list') }}";
</script>